account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('', views.user_profile, name='user_status'),
    path('login', views.user_login, name='login'),
    path('user_detail/<int:user_id>/', views.user_detail, name='user_detail'),
    path('profile/<int:user_id>', views.user_profile, name='user_profile'),
    path('logout', views.logout_view, name='logout'),
    path('change_first_name/<int:user_id>/', views.change_first_name, name='change_first_name'),
    path('change_last_name/<int:user_id>/', views.change_last_name, name='change_last_name'),
    path('change_email/<int:user_id>/', views.change_email, name='change_email'),
    path('password_reset/<int:user_id>', views.password_reset, name='password_reset'),
    path('change_department/<int:user_id>/', views.change_department, name='change_department'),
    path('change_password', views.change_password, name='change_password'),
    path('login_change/<int:user_id>/', views.login_change, name='login_change')
]

ams/urls.py
from django.urls import path
from . import views

app_name = 'ams'
urlpatterns = [
    path('', views.ams, name='ams'),
    path('ams_create/', views.ams_create, name='ams_create'),
    path('export_xls_ams/', views.export_xls_ams, name='export_xls_ams'),
    path('delete_ams/<int:ams_id>/', views.delete_ams, name='delete_ams'),
    path('ams_detail/<int:ams_id>/<str:msg>/', views.ams_detail, name='ams_detail'),
    path('ams_detail/<int:ams_id>/', views.ams_detail, name='ams_detail'),
    path('change_height/<int:ams_id>/', views.change_height, name='change_height'),
    path('change_weight/<int:ams_id>/', views.change_weight, name='change_weight'),
    path('change_type/<int:ams_id>/', views.change_type, name='change_type'),
    path('change_date/<int:ams_id>/', views.change_date, name='change_date'),
    path('change_scheme/<int:ams_id>/', views.change_scheme, name='change_scheme'),
    path('delete_scheme/<int:ams_id>/', views.delete_scheme, name='delete_scheme'),
    path('foto_ams_add/<int:ams_id>', views.foto_ams_add, name='foto_ams_add'),
    path('foto_delete/<int:foto_id>/', views.foto_delete, name='foto_delete'),
    path('add_protocol/<int:ams_id>/', views.add_protocol, name='add_protocol'),
    path('add_diagnostic/<int:ams_id>/', views.add_diagnostic, name='add_diagnostic'),
    path('add_project/<int:ams_id>/', views.add_project, name='add_project'),
    path('add_sez/<int:ams_id>/', views.add_sez, name='add_sez'),
    path('add_inventory/<int:ams_id>/', views.add_inventory, name='add_inventory'),
    path('select_inventory/<int:ams_id>', views.select_inventory, name='select_inventory'),
    path('add_passport/<int:ams_id>', views.add_passport, name='add_passport'),
    path('delete_passport/<int:ams_id>/', views.delete_passport, name='delete_passport'),
    path('project_list/<int:ams_id>/', views.project_list, name='project_list'),
    path('project_list/<int:ams_id>/<str:msg>/', views.project_list, name='project_list'),
    path('project_delete/<int:project_id>/', views.project_delete, name='project_delete'),
    path('add_project_list/<int:ams_id>/', views.add_project_list, name='add_project_list'),
    path('do_list/<int:ams_id>/', views.do_list, name='do_list'),
    path('do_list/<int:ams_id>/<str:msg>/', views.do_list, name='do_list'),
    path('do_delete/<int:do_id>/', views.do_delete, name='do_delete'),
    path('add_do_list/<int:ams_id>/', views.add_do_list, name='add_do_list'),
    path('measurement_list/<int:ams_id>/', views.measurement_list, name='measurement_list'),
    path('measurement_list/<int:ams_id>//<str:msg>', views.measurement_list, name='measurement_list'),
    path('measurement_delete/<int:measurement_id>/', views.measurement_delete, name='measurement_delete'),
    path('add_measurement_list/<int:ams_id>/', views.add_measurement_list, name='add_measurement_list'),
    path('sez_list/<int:ams_id>/', views.sez_list, name='sez_list'),
    path('sez_list/<int:ams_id>/<str:msg>', views.sez_list, name='sez_list'),
    path('sez_delete/<int:sez_id>/', views.sez_delete, name='sez_delete'),
    path('add_sez_list/<int:ams_id>/', views.add_sez_list, name='add_sez_list'),
    path('foto_list/<int:ams_id>/', views.foto_list, name='foto_list'),
    path('foto_list/<int:ams_id>/<str:msg>/', views.foto_list, name='foto_list'),
    path('foto_list_delete/<int:foto_id>', views.foto_list_delete, name='foto_list_delete'),
    path('add_foto_list/<int:ams_id>/', views.add_foto_list, name='add_foto_list')
    ]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('objects/', views.objects_list, name='objects'),
    path('objects/<str:msg>/', views.objects_list, name='objects'),
    path('object_index/', views.object_index, name='object_index'),
    path('create_object/', views.create_object, name='create_object'),
    path('create_rrl/', views.create_rrl, name='create_rrl'),
    path('object_detail/<int:name>/<str:msg>/', views.object_detail, name='object_detail'),
    path('object_detail/<int:name>/', views.object_detail, name='object_detail'),
    path('upload/', views.upload_xls, name='upload_xls'),
    path('upload_choice/<object_id>/', views.upload_choice, name='upload_choice'),
    path('import_data/<choice>/<int:object_id>/', views.import_data, name='import_data'),
    path('structure/', views.structure, name='structure'),
    path('export_xls_department/<ceh>/', views.export_xls_department, name='export_xls_department'),
    path('rrl_line/', views.rrl_line, name='rrl_line'),
    path('change_rrl/<int:pk>/', views.change_rrl, name='change_rrl'),
    path('delete_rrl/<int:pk>/', views.delete_rrl, name='delete_rrl'),
    path('export_objects/', views.export_objects, name='export_objects'),
    path('delete_object/<int:pk>/', views.delete_object, name='delete_object'),
    path('change_object/<int:pk>/', views.change_object, name='change_object'),
    path('ozp_create/', views.ozp_create, name='ozp_create'),
    path('ozp', views.ozp, name='ozp'),
    path('ozp_details/<int:ozp_id>/', views.ozp_details, name='ozp_details'),
    path('ozp_zamechanie_change/<int:ozp_id>/', views.ozp_zamechanie_change, name='ozp_zamechanie_change'),
    path('ozp_normative_change/<int:ozp_id>/', views.ozp_normative_change, name='ozp_normative_change'),
    path('srok_ustranenia_change/<int:ozp_id>/', views.srok_ustranenia_change, name='srok_ustranenia_change'),
    path('control_srok_change/<int:ozp_id>/', views.control_srok_change, name='control_srok_change'),
    path('foto_zamechanie_add/<int:ozp_id>/', views.foto_zamechanie_add, name='foto_zamechanie_add'),
    path('foto_do_delete/<int:f_id>/', views.foto_do_delete, name='foto_do_delete'),
    path('posle_foto_delete/<int:f_id>/', views.posle_foto_delete, name='posle_foto_delete'),
    path('foto_vipolnenie_add/<int:ozp_id>/', views.foto_vipolnenie_add, name='foto_vipolnenie_add'),
    path('accept/<int:ozp_id>/', views.accept, name='accept'),
    path('podano_na_vipolnenie/<int:ozp_id>/', views.podano_na_vipolnenie, name='podano_na_vipolnenie'),
    path('not_accept/<int:ozp_id>/', views.not_accept, name='not_accept'),
    path('export_xls_ozp/', views.export_xls_ozp, name='export_xls_ozp'),
    path('delete_ozp/<int:ozp_id>', views.delete_ozp, name='delete_ozp'),
    path('user_delete/<int:user_id>/', views.user_delete, name='user_delete'),
    path('user_create', views.user_create, name='user_create'),
    path('ajax/load-uchastok/', views.load_uchastok, name='ajax_uchastok'),
    path('ajax/load-objects/', views.load_objects, name='ajax_load_objects'),
    path('ajax/load-object-uchastok/', views.load_object_uchastok, name='load_object_uchastok'),
    path('tu_create/', views.tu_create, name='tu_create'),
    path('tu_list/', views.tu_list, name='tu_list'),
    path('delete_tu/<int:tu_id>/', views.delete_tu, name='delete_tu'),
    path('tehdoc_list/', views.tehdoc_list, name='tehdoc_list'),
    path('tehdoc_create/', views.tehdoc_create, name='tehdoc_create'),
    path('delete_tehdoc/<int:tehdoc_id>/', views.delete_tehdoc, name='delete_tehdoc'),
    path('scheme_list/', views.scheme_list, name='scheme_list'),
    path('scheme_create', views.scheme_create, name='scheme_create'),
    path('scheme_delete/<int:scheme_id>/', views.scheme_delete, name='scheme_delete'),
    path('change_object_name/<int:obj_id>/', views.change_object_name, name='change_object_name'),
    path('change_object_uchastok/<int:obj_id>/', views.change_object_uchastok, name='change_object_uchastok'),
    path('change_coordinats/<int:obj_id>/', views.change_coordinats, name='change_coordinats'),
    path('change_address/<int:obj_id>/', views.change_address, name='change_address'),
    path('change_district/<int:obj_id>/', views.change_district, name='change_district'),
    path('add_object_foto/<int:obj_id>/', views.add_object_foto, name='add_object_foto'),
    path('foto_object_delete/<int:foto_id>/', views.foto_object_delete, name='foto_object_delete'),
    path('delete_object/<int:obj_id>', views.delete_object, name='delete_object'),
    path('object_foto_list/', views.object_foto_list, name='object_foto_list'),
    path('object_foto_list/<str:msg>/', views.object_foto_list, name='object_foto_list'),
    path('foto_add_list/', views.foto_add_list, name='foto_add_list'),
    path('foto_list_delete/<int:foto_id>', views.foto_list_delete, name='foto_list_delete')
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('ams/', include('ams.urls')),
    path('rich/', include('rich.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                             document_root=settings.MEDIA_ROOT)

main/forms.py
from django.forms import ModelForm, TextInput, Textarea, DateInput
from .models import Object, RrlLine, Position, UploadedData, Choice, Department, Technicheskie_usloviya, \
    Technicheskaya_documentacia, Scheme, Object_Foto
from django import forms


class ObjectForm(ModelForm):
    class Meta:
        model = Object
        fields = ['object_name', 'rrl_line', 'uchastok']

    uchastok = forms.ModelChoiceField(queryset=Department.objects.filter(is_prod=True),
                                      empty_label='Выберите участок связи', label='Выберите подразделение')


class RrlForm(ModelForm):
    class Meta:
        model = RrlLine
        fields = ['rrl_line_name', 'station_count', 'bandwidth']


class PositionForm(ModelForm):
    class Meta:
        model = Position
        fields = ['latitude_degrees', 'latitude_minutes', 'latitude_seconds', 'longitude_degrees', 'longitude_minutes',
                  'longitude_seconds', 'address', 'district']
        widgets = {
            'address': Textarea(attrs={'rows': '3', 'cols': '60', 'class': 'position_textarea'}),
            'district': Textarea(attrs={'rows': '3', 'cols': '60', 'class': 'position_textarea'})
        }


class UploadXlsForm(ModelForm):
    class Meta:
        model = UploadedData
        fields = ['file']


class UploadChoiceForm(ModelForm):
    class Meta:
        model = Choice
        fields = ['sheet', 'row']


class ImportForm(ModelForm):
    class Meta:
        model = Choice
        fields = ['object_name', 'coords_lat', 'coords_lon', 'district', 'address']


class DepartmentForm(ModelForm):
    class Meta:
        model = Department
        fields = ['ceh', 'uchastok']


class FilterForm(forms.Form):
    ceh_list = Department.objects.filter(is_prod=True).values_list('ceh', flat=True).order_by('ceh').distinct()
    ceh = forms.ModelChoiceField(queryset=ceh_list, empty_label='все', label='Фильтровать по цеху', required=False)
    uchastok = forms.ModelChoiceField(queryset=Department.objects.filter(is_prod=True).values_list('uchastok',
                                                                                                   flat=True),
                                      empty_label='все', label='Фильтровать по участку', required=False)
    object = forms.ModelChoiceField(queryset=Object.objects.all().values_list('object_name', flat=True),
                                    empty_label='все', label='Фильтровать по объекту', required=False)



class Tu_Create_Form(ModelForm):
    class Meta:
        model = Technicheskie_usloviya
        fields = ['name', 'organization', 'proekt', 'object', 'doc', 'date', 'expire_date', 'description']

        widgets = {
            'date': DateInput(attrs={'type': 'date'}),
            'expire_date': DateInput(attrs={'type': 'date'}),
            'description': Textarea(attrs={'rows': '3', 'cols': '60', 'class': 'position_textarea'}),
            'name': TextInput(attrs={'size': '100'}),
            'organization': TextInput(attrs={'size': '100'}),
            'proekt': TextInput(attrs={'size': '100'})
        }


class Tehdoc_Create_Form(ModelForm):
    class Meta:
        model = Technicheskaya_documentacia
        fields = ['name', 'object', 'doc', 'date', 'description']

        widgets = {
            'date': DateInput(attrs={'type': 'date'}),
            'description': Textarea(attrs={'rows': '3', 'cols': '60', 'class': 'position_textarea'}),
            'name': TextInput(attrs={'size': '100'}),
        }


class Scheme_Create_Form(ModelForm):
    class Meta:
        model = Scheme
        fields = ['name', 'object', 'doc', 'date']

        widgets = {
            'date': DateInput(attrs={'type': 'date'}),
            'name': TextInput(attrs={'size': '100'}),
        }


class Object_Name_Form(ModelForm):
    class Meta:
        model = Object
        fields = ['object_name']
        widgets = {
            'object_name': TextInput(attrs={'size': '50'}),
        }


class Object_Uchastok_Form(forms.Form):
    uchastok = forms.ModelChoiceField(queryset=Department.objects.filter(is_prod=True))


class Coordinat_Form(ModelForm):
    class Meta:
        model = Position
        fields = ['latitude_degrees', 'latitude_minutes', 'latitude_seconds', 'longitude_degrees', 'longitude_minutes',
                  'longitude_seconds']


class Object_Address_Form(ModelForm):
    class Meta:
        model = Position
        fields = ['address']
        widgets = {
            'address': TextInput(attrs={'size': '50'}),
        }


class Object_District_Form(ModelForm):
    class Meta:
        model = Position
        fields = ['district']
        widgets = {
            'district': TextInput(attrs={'size': '50'}),
        }


class Object_Foto_Form(ModelForm):
    class Meta:
        model = Object_Foto
        fields = ['year', 'foto']
        widgets = {
            'year': DateInput(attrs={'type': 'date'}),
            'foto_name': TextInput(attrs={'size': '50'})
        }


class List_Foto_Form(ModelForm):
    class Meta:
        model = Object_Foto
        fields = ['year', 'foto', 'object']
        widgets = {
            'year': DateInput(attrs={'type': 'date'}),
            'foto_name': TextInput(attrs={'size': '50'})
        }

main/templates/main/templates/object_creation.html
{% extends "main/templates/layout.html" %}
{% block title %}Создание объекта{% endblock %}
{% block content %}
    <div lass="creation_form">
    <div>
        <p>Для создания объекта заполните представленную форму:</p>
    </div>
    <div>
        <form action="{% url 'main:create_object' %}" method="post">
            {{ obj_form.as_p }}
            Укажите координаты объекта:
            <div class="coordinats">
                <table>
                <tr>
                    <td>Северной широты:</td>
                    <td>{{ pos_form.latitude_degrees }}°{{ pos_form.latitude_minutes }}'{{ pos_form.latitude_seconds }}"</td>
                </tr>
                <tr>
                    <td>Восточной долготы:</td>
                    <td>{{ pos_form.longitude_degrees }}°{{ pos_form.longitude_minutes }}'{{ pos_form.longitude_seconds }}"</td>
                </tr>
                <tr>
                    <td>Адрес:</td>
                    <td>{{ pos_form.address}}</td>
                </tr>
                <tr>
                    <td>Район:</td>
                    <td>{{ pos_form.district}}</td>
                </tr>
                </table>
            </div>
            {% csrf_token %}
            <div class="account-button">
                <input type="submit" value="Создать объект">
            </div>
        </form>
    </div>
    <div>{{ msg }}</div>
    </div>
{% endblock %}

main/templates/main/templates/ozp.html
{% extends "main/templates/layout.html" %}
{% block title %}Список объектов{% endblock %}
{% block content %}
    <div class="button-bar">
        <span>
            <form action="{% url 'main:ozp_create' %}">
                <button type="submit" value="Создать">Создать запись</button>
            </form>
        </span>
        <span>
            <a href="{% url 'main:export_xls_ozp' %}?{{ request.GET.urlencode }}">
                <button type="submit">Выгрузить</button>
            </a>
        </span>
        <div id="filter-button">
            <span>
                {% if filtered_by == '' %} Фильтрация отсутствует.
                {% else %} Объекты отфильтрованы по: {{ filtered_by }}</span>
                {% endif %}
            <button type="submit" form="filter_reset" value="Сбросить" >Сбросить</button>
            <input type="button" value="Фильтр" onmousedown="showhide('filter')" id="filter-button-dynamic">
            <form id="filter_reset">
                <a href={% url 'main:ozp' %}>
                </a>
            </form>
        </div>
    </div>
    <div id="filter">
            <div class="filter-content">
                <form id="filter_form" method="get" action={% url 'main:ozp' %}>
                    {{ filter_form.as_p }}
                    <span>Фильтровать по выполненным:</span>
                    <p>
                        <select name="vipolnenie" form="filter_form">
                            <option value="all">Показать все</option>
                            <option value="1">Показать только выполненные</option>
                            <option value="0">Показать только не выполненные</option>
                        </select>
                    </p>
                    <span>Фильтровать по заявленным на выполнение:</span>
                    <p>
                        <select name="na_vipolnenie" form="filter_form">
                            <option value="all">Показать все</option>
                            <option value="1">Показать только заявленные</option>
                            <option value="0">Показать только незаявленные</option>
                        </select>
                    </p>
                    <span>Фильтровать по году выполнения:</span>
                    <p>
                        {% for i in year %}
                        <input type="checkbox" name="year_{{ i }}" value="{{ i }}" checked>{{ i }}
                        {% endfor %}
                    </p>
                    <span>Фильтровать по замечаниям которые необходимо выполнить в течении месяца:</span>
                    <p>
                        <select name="this_month" form="filter_form">
                            <option value="all">Показать все</option>
                            <option value="this_month">Показать замечания со сроком выполнения в этом месяце</option>
                        </select>
                    </p>
                </form>
            </div>
            <div id="filter-button-bar">
                <button type="submit" form="filter_form" value="Применить">Применить</button>
            </div>
        <!-----------------------------------------ajax------------------------------------------------------------>
        <script src="/static/main/script/jquery.js"></script>
        <script src="/static/main/script/filter.js"></script>
    <!-----------------------------------------ajax------------------------------------------------------------>
    </div>
    <div class="content">
        <div class="table">
            <table>
                <tr class="head_row">
                    <th>К замечанию</th>
                    <th>Объект</th>
                    <th>Содержание замечания</th>
                    <th>Нормативная документация</th>
                    <th>Фото замечания</th>
                    <th>Контрольная дата</th>
                    <th>Дата устранения</th>
                    <th>Подано на устранение</th>
                    <th>Выполнение</th>
                </tr>
                {% if objectlist %}
                    {% for i in objectlist %}
                        <tr class="table_row">
                            <td align="center">
                                <a href="{{ i.get_absolute_url }}" class="ozp-link">
                                <img src="static/main/img/strelka.png" height="50" width="50">
                                </a>
                            </td>
                            <td>
                                <a href="{{ i.object_name.get_absolute_url }}" >
                                    {{ i.object_name.object_name }}
                                </a>
                            </td>
                            <td>{{ i.zamechanie_ozp }}</td>
                            <td>{{ i.normative_documentation }}</td>
                            <td class="foto_collumn">
                                {% for z in i.foto_zamechania.all %}
                                    <a href="{{ z.foto.url }}" target="_blank">
                                        <img src="{{ z.foto.url }}" height="50">
                                    </a>
                                {% endfor %}
                            </td>
                            <td align="center">
                                {% if i.control_date %}
                                    {{ i.control_date }}
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                            <td align="center">
                                {% if i.zakrytie_date %}
                                    {{ i.zakrytie_date }}
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                            <td align="center">
                                {% if i.podano_na_vipolnenie.podano == 1 %}
                                    <img src="static/main/img/Exclamation-Mark-Transparent-PNG.png" height="20" width="20">
                                {% endif %}
                            </td>
                            <td align="center">
                                {% if i.is_done == 0 %}
                                    <img src="static/main/img/free-png.ru-388.png" height="20" width="20">
                                {% else %}
                                    <img src="static/main/img/free-png.ru-39.png" height="20" width="20">
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <p>Замечания отсутствуют</p>
                {% endif %}
            </table>
        </div>
    </div>
{% endblock %}

main/templates/main/templates/ozp_creation.html
{% extends "main/templates/layout.html" %}
{% block title %}Создание замечания{% endblock %}
{% block content %}
    <div class="creation_form">
        <p>Для создания замечания заполните представленную форму:</p>
        <form action="{% url 'main:ozp_create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
        <p>
            <label for="associated_object">Выберите объект на котором выявлено замечание:</label>
        </p>
        <p>
            <select name="associated_object" id="associated_object" required>
                {% for i in objects %}
                    <option value="{{ i }}">{{ i }}</option>
                {% endfor %}
            </select>
        </p>
        <p>
            <label for="zamechanie_ozp">Введите содержание замечания:</label>
        </p>
        <p>
            <textarea name="zamechanie_ozp" id="zamechanie_ozp" required maxlength="500" cols="50" rows="5"></textarea>
        </p>
        <p>
            <label for="normative_documentation">Нормативная документация:</label>
        </p>
        <p>
            <textarea name="normative_documentation" id="normative_documentation" maxlength="100" maxlength="500" cols="50" rows="5"></textarea>
        </p>
        <p>
            <label for="foto_do">Выберите фото замечания:</label>
        </p>
            <input type="file" name="foto_do" id="foto_do" required>
        <p>
        <div class="account-button">
            <input type="submit" value="Создать">
        </div>
        </form>
        <p>{{ msg }}</p>
    </div>
{% endblock %}

main/templates/main/templates/rrl.html
{% extends "main/templates/layout.html" %}
{% block title %}Список объектов{% endblock %}
{% block content %}
    <div class="button-bar">
        <span>
            <form action="{% url 'main:create_rrl' %}">
                <button type="submit" value="Создать">Создать запись</button>
            </form>
        </span>
    </div>
    <div class="content">
        <div class="table">
        <table>
            <tr class="head_row">
                <th>Наименование линии</th>
                <th>Количество станций</th>
                <th>Полоса пропускания</th>
                <th></th>
                <th></th>
            </tr>
            {% if objectlist %}
                {% for i in objectlist %}
                    <tr class="table_row">
                        <td>{{ i.rrl_line_name }}</td>
                        <td>{{ i.get_station_count_field }}</td>
                        <td>{{ i.get_bandwidth_field }}</td>
                        <td align="center">
                            <form action="{% url 'main:change_rrl' i.pk %}">
                                <button>Изменить</button>
                            </form>
                        </td>
                        <td align="center">
                            <form method="post" action="{% url 'main:delete_rrl' i.pk %}">
                                {% csrf_token %}
                                <button type="submit">Удалить</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <p>Записи отсутствуют</p>
            {% endif %}
        </table>
        </div>
    </div>
{% endblock %}

main/templates/main/templates/structure.html
{% extends "main/templates/layout.html" %}
{% block title %}Список объектов{% endblock %}
{% block content %}
    <div class="button-bar">
        <span>
            <form action="{% url 'main:user_create' %}">
                <button type="submit" value="Создать">Создать</button>
            </form>
        </span>
        <span>
            {{ msg }}
        </span>
    <!-------------------------------------------------------------------->
        <div id="filter-button">
            <span>
                {% if filtered_by == 'all' %} Фильтрация отсутствует.
                {% else %} Объекты отфильтрованы по: {{ filtered_by }}</span>
                {% endif %}
            <button type="submit" form="filter_reset" value="Сбросить" >Сбросить</button>
            <input type="button" value="Фильтр" onmousedown="showhide('filter')" id="filter-button-dynamic">
            <form id="filter_reset">
                <a href={% url 'main:structure' %}>
                </a>
            </form>
        </div>
    <!-------------------------------------------------------------------->
    </div>
    <!-------------------------------------------------------------------->
    <div id="filter">
        <div class="filter-content">
            <form id="filter_form" method="get" action={% url 'main:structure' %}>
                <span>Фильтровать по подразделению:</span>
                <p>
                    <select name="department" form="filter_form">
                         <option value="all" selected>Все</option>
                         {% for i in department %}
                            <option value="{{ i.id }}">{{ i }}</option>
                         {% endfor %}
                    </select>
                </p>
            </form>
        </div>
        <div id="filter-button-bar">
            <button type="submit" form="filter_form" value="Применить">Применить</button>
        </div>
    </div>
    <!-------------------------------------------------------------------->
    <div class="content">
        <!-------------------------------------------------------------------->
        {% for i in objectlist %}
            <div id="user_delete_{{ i.id }}" class="change_form_ozp">
                <form method="post" action="{% url 'main:user_delete' i.id %}">
                    {% csrf_token %}
                    Вы действительно хотите удалить выбранного пользователя {{ i.username }}???
                    <br><br>
                    <input type="submit" value="Удалить">
                    <button onmousedown="showhide_changeform('user_delete_{{ i.id }}')" class="close_button">
                        <i class="fa-solid fa-xmark"></i>
                    </button>
                </form>
            </div>
        {% endfor %}
        <!-------------------------------------------------------------------->
        <div class="table">
            <table>
                <tr>
                    <th>Имя пользователя</th>
                    <th>Пользователь</th>
                    <th>Подразделение</th>
                    <th>Статус</th>
                    <th width="30 px">Удалить пользователя</th>
                </tr>
            <!-------------------------------------------------------------------->
                <tr>
            {% if objectlist %}
                {% for i in objectlist %}
                    <tr>
                        <td><a href="{% url 'account:user_detail' i.id %}">{{ i }}</a></td>
                        <td>{{ i.first_name }} {{ i.last_name }}</td>
                        <td>{{ i.profile.department }}</td>
                        <td align="center">
                            {% if i.is_online %}
                                <svg height="20" width="20">
                                    <circle cx="10" cy="10" r="5" stroke="green" stroke-width="3" fill="green" />
                                </svg>
                            {% else %}
                                <svg height="20" width="20">
                                    <circle cx="10" cy="10" r="5" stroke="red" stroke-width="3" fill="red" />
                                </svg>
                            {% endif %}
                        </td>
                        <td align="center">
                            <button onmousedown="showhide_changeform('user_delete_{{ i.id }}')" class="close_button">
                                    <i class="fa-solid fa-trash"></i>
                            </button>
                        </td>
                    </tr>
                {% endfor %}
                <!-------------------------------------------------------------------->
            {% else %}
                <p>Записи отсутствуют</p>
            {% endif %}
            </table>
        </div>
    </div>
{% endblock %}