ams/urls.py
from django.urls import path
from . import views

app_name = 'ams'
urlpatterns = [
    path('', views.ams, name='ams'),
    path('ams_create/', views.ams_create, name='ams_create'),
    path('export_xls_ams/', views.export_xls_ams, name='export_xls_ams'),
    path('delete_ams/<int:ams_id>/', views.delete_ams, name='delete_ams'),
    path('ams_detail/<int:ams_id>/<str:msg>/', views.ams_detail, name='ams_detail'),
    path('ams_detail/<int:ams_id>/', views.ams_detail, name='ams_detail'),
    path('change_height/<int:ams_id>/', views.change_height, name='change_height'),
    path('change_weight/<int:ams_id>/', views.change_weight, name='change_weight'),
    path('change_type/<int:ams_id>/', views.change_type, name='change_type'),
    path('change_date/<int:ams_id>/', views.change_date, name='change_date'),
    path('change_scheme/<int:ams_id>/', views.change_scheme, name='change_scheme'),
    path('delete_scheme/<int:ams_id>/', views.delete_scheme, name='delete_scheme'),
    path('foto_ams_add/<int:ams_id>', views.foto_ams_add, name='foto_ams_add'),
    path('foto_delete/<int:foto_id>/', views.foto_delete, name='foto_delete'),
    path('add_protocol/<int:ams_id>/', views.add_protocol, name='add_protocol'),
    path('add_diagnostic/<int:ams_id>/', views.add_diagnostic, name='add_diagnostic'),
    path('add_project/<int:ams_id>/', views.add_project, name='add_project'),
    path('add_sez/<int:ams_id>/', views.add_sez, name='add_sez'),
    path('add_inventory/<int:ams_id>/', views.add_inventory, name='add_inventory'),
    path('select_inventory/<int:ams_id>', views.select_inventory, name='select_inventory'),
    path('add_passport/<int:ams_id>', views.add_passport, name='add_passport'),
    path('delete_passport/<int:ams_id>/', views.delete_passport, name='delete_passport'),
    path('project_list/<int:ams_id>/', views.project_list, name='project_list'),
    path('project_list/<int:ams_id>/<str:msg>/', views.project_list, name='project_list'),
    path('project_delete/<int:project_id>/', views.project_delete, name='project_delete'),
    path('add_project_list/<int:ams_id>/', views.add_project_list, name='add_project_list'),
    path('do_list/<int:ams_id>/', views.do_list, name='do_list'),
    path('do_list/<int:ams_id>/<str:msg>/', views.do_list, name='do_list'),
    path('do_delete/<int:do_id>/', views.do_delete, name='do_delete'),
    path('add_do_list/<int:ams_id>/', views.add_do_list, name='add_do_list'),
    path('measurement_list/<int:ams_id>/', views.measurement_list, name='measurement_list'),
    path('measurement_list/<int:ams_id>//<str:msg>', views.measurement_list, name='measurement_list'),
    path('measurement_delete/<int:measurement_id>/', views.measurement_delete, name='measurement_delete'),
    path('add_measurement_list/<int:ams_id>/', views.add_measurement_list, name='add_measurement_list'),
    path('sez_list/<int:ams_id>/', views.sez_list, name='sez_list'),
    path('sez_list/<int:ams_id>/<str:msg>', views.sez_list, name='sez_list'),
    path('sez_delete/<int:sez_id>/', views.sez_delete, name='sez_delete'),
    path('add_sez_list/<int:ams_id>/', views.add_sez_list, name='add_sez_list'),
    path('foto_list/<int:ams_id>/', views.foto_list, name='foto_list'),
    path('foto_list/<int:ams_id>/<str:msg>/', views.foto_list, name='foto_list'),
    path('foto_list_delete/<int:foto_id>', views.foto_list_delete, name='foto_list_delete'),
    path('add_foto_list/<int:ams_id>/', views.add_foto_list, name='add_foto_list')
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('ams/', include('ams.urls')),
    path('rich/', include('rich.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                             document_root=settings.MEDIA_ROOT)

rich/urls.py
from django.urls import path
from . import views

app_name = 'rich'
urlpatterns = [
    path('', views.rich_index, name='rich_index'),
    path('res_create/', views.res_creation, name='res_create'),
    path('res_detail/<int:id>/', views.res_detail, name='res_detail'),
    path('change_name/<int:id>/', views.change_name, name='change_name'),
    path('change_object/<int:id>/', views.change_object, name='change_object'),
    path('change_rich/<int:id>/', views.change_rich, name='change_rich'),
    path('add_rich/<int:id>/', views.add_rich, name='add_rich'),
    path('change_registration/<int:id>/', views.change_registration, name='change_registration'),
    path('add_registration/<int:id>/', views.add_registration, name='add_registration'),
    path('change_radio_class/<int:id>', views.change_radio_class, name='change_radio_class'),
    path('antenna_height_change/<int:id>', views.antenna_height_change, name='antenna_height_change'),
    path('antenna_azimuth_change/<int:id>', views.antenna_azimuth_change, name='antenna_azimuth_change'),
    path('antenna_gain_change/<int:id>', views.antenna_gain_change, name='antenna_gain_change'),
    path('antenna_polarization_change/<int:id>/', views.antenna_polarization_change, name='antenna_polarization_change'),
    path('rich_app_index', views.rich_app_index, name='rich_app_index'),
    path('rich_list', views.rich_list, name='rich_list'),
    path('rich_create', views.rich_create, name='rich_create'),
    path('delete_rich/<int:id>', views.delete_rich, name='delete_rich'),
    path('export_xls_rich', views.export_xls_rich, name='export_xls_rich'),
    path('reg_list', views.reg_list, name='reg_list'),
    path('delete_reg/<int:key>', views.delete_reg, name='delete_reg'),
    path('reg_create', views.reg_create, name='reg_create'),
    path('ajax/load-res/', views.load_res, name='ajax_load_res'),
    path('export_xls_reg/', views.export_xls_reg, name='export_xls_reg'),
    path('res_export_xls/', views.res_export_xls, name='res_export_xls'),
    path('delete_res/<int:key>', views.delete_res, name='delete_res'),
    path('equip_list/', views.equip_list, name='equip_list'),
    path('equip_delete/<int:key>/', views.equip_delete, name='equip_delete'),
    path('equip_create/', views.equip_create, name='equip_create'),
    path('add_equipment/<int:key>/', views.add_equipment, name='add_equipment'),
    path('change_equipment/<int:key>', views.change_equipment, name='change_equipment'),
    path('protokol_list/<int:key>/', views.protokol_list, name='protokol_list'),
    path('protocol_delete/<int:key>', views.protocol_delete, name='protocol_delete'),
    path('add_res_protokol/<int:key>/', views.add_res_protokol, name='add_res_protokol'),
    path('add_res_protokol_list/<int:key>/', views.add_res_protokol_list, name='add_res_protokol_list')
]

ams/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.shortcuts import render, redirect
from openpyxl import Workbook
from openpyxl.styles import Border, Side, Alignment, Font
from openpyxl.styles.numbers import BUILTIN_FORMATS

from ams.forms import AmsForm, AmsTypeForm, SchemeForm, FotoAmsForm, ProtocolForm, DiagnosticForm, ProjectForm, \
    SezForm, InventoryForm, PassportForm
from ams.models import Ams, Foto_Ams, Measurments, Diagnostic, Project, Sez, Inventory
from main.forms import FilterForm
from main.scripts import form_errors_text, object_filter, is_staff


@login_required(login_url='account:login')
def ams(request):
    filter_form = FilterForm()
    object_list = Ams.objects.all()
    filtered_by = []
    if request.method == 'GET':
        data = FilterForm(request.GET or None)
        objects, filtered_by = object_filter(data)
        object_list = object_list.filter(object_name__in=objects)
        try:
            min_visota = int(request.GET.get('min_visota'))
            max_visota = int(request.GET.get('max_visota'))
            otklonenie = request.GET.get('otklonenie')
            if min_visota >= max_visota or min_visota < 0 or max_visota < 0 or max_visota > 300 or min_visota == '' \
                    or max_visota == '':
                msg = 'Вы указали неверное значение высоты АМС'
                filtered_by_str = ' '.join(filtered_by)
                context = {'object': object_list, 'filter_form': data, 'filtered_by': filtered_by_str, 'msg': msg}
                return render(request, 'ams/templates/ams_list.html', context)
            elif min_visota == 0 and max_visota == 300:
                pass
            else:
                object_list = object_list.filter(height__gte=min_visota, height__lte=max_visota)
                filtered_by.append('Высоте')
            if otklonenie == '1':
                measurments = Measurments.objects.filter(is_otklonenie=True, is_last=True)
                object_list = object_list.filter(protocol__in=measurments)
                filtered_by.append('АМС с отклонением')
            elif otklonenie == '0':
                measurments = Measurments.objects.filter(is_otklonenie=False, is_last=True)
                object_list = object_list.filter(protocol__in=measurments)
                filtered_by.append('АМС без отклонения')
            elif otklonenie == '2':
                object_list = object_list.filter(protocol=None)
                filtered_by.append('АМС без измерений вертикальности')
        except (ValueError, TypeError):
            filtered_by_str = ' '.join(filtered_by)
            context = {'object': object_list, 'filter_form': data, 'filtered_by': filtered_by_str}
            return render(request, 'ams/templates/ams_list.html', context)
    filtered_by_str = ' '.join(filtered_by)
    context = {'object': object_list, 'filter_form': filter_form, 'filtered_by': filtered_by_str}
    return render(request, 'ams/templates/ams_list.html', context)


@login_required(login_url='account:login')
@is_staff
def ams_create(request):
    form = AmsForm(request.POST or None)
    msg = ''
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('ams:ams')
        else:
            msg = form_errors_text(form)
    context = {'form': form, 'msg': msg}
    return render(request, 'ams/templates/ams_creation.html', context)


@login_required(login_url='account:login')
def export_xls_ams(request):
    object_list = Ams.objects.all()
    if request.method == 'GET':
        try:
            data = FilterForm(request.GET or None)
            objects, filtered_by = object_filter(data)
            object_list = object_list.filter(object_name__in=objects)
            min_visota = int(request.GET.get('min_visota'))
            max_visota = int(request.GET.get('max_visota'))
            otklonenie = request.GET.get('otklonenie')
            if min_visota >= max_visota or min_visota < 0 or max_visota < 0 or max_visota > 300 or min_visota == '' \
                    or max_visota == '':
                msg = 'Вы указали неверное значение высоты АМС'
                filtered_by_str = ' '.join(filtered_by)
                context = {'object': object_list, 'filter_form': data, 'filtered_by': filtered_by_str, 'msg': msg}
                return render(request, 'ams/templates/ams_list.html', context)
            elif min_visota == 0 and max_visota == 300:
                pass
            else:
                object_list = object_list.filter(height__gte=min_visota, height__lte=max_visota)
            if otklonenie == '1':
                measurments = Measurments.objects.filter(is_otklonenie=True, is_last=True)
                object_list = object_list.filter(protocol__in=measurments)
            elif otklonenie == '0':
                measurments = Measurments.objects.filter(is_otklonenie=False, is_last=True)
                object_list = object_list.filter(protocol__in=measurments)
            elif otklonenie == '2':
                object_list = object_list.filter(protocol=None)
        except (ValueError, TypeError):
            pass
        # выгрузка в xls -----------------------------------------------------
        response = HttpResponse(content_type='application/ms-excel')
        response['Content-Disposition'] = 'attachment; filename="ams.xlsx"'
        wb = Workbook()
        rows = object_list
        ws = wb.active
        row_num = 1
        columns = ['Объект', 'Высота', 'Вес', 'Тип', 'Дата ввода в эксплуатацию', 'Количество ярусов оттяжек',
                   'Инвентарный номер', 'Владелец', 'Наименование ОС', 'Отклонение', 'Допуск']
        font = Font(name='TimesNewRoman', sz=11, bold=True)
        font2 = Font(name='TimesNewRoman', sz=11, bold=False)
        border = Border(left=Side(border_style='thin', color='FF000000'),
                        right=Side(border_style='thin', color='FF000000'),
                        top=Side(border_style='thin', color='FF000000'),
                        bottom=Side(border_style='thin', color='FF000000'))
        alignment = Alignment(horizontal='center',
                              vertical='center',
                              text_rotation=0,
                              wrap_text=True,
                              shrink_to_fit=False,
                              indent=0)
        for col_num in range(len(columns)):
            ws.cell(row_num, col_num + 1, columns[col_num])
            ws.cell(row_num, col_num + 1).font = font
            ws.cell(row_num, col_num + 1).border = border
            ws.cell(row_num, col_num + 1).alignment = alignment
        ws.column_dimensions['A'].width = 30
        ws.column_dimensions['B'].width = 10
        ws.column_dimensions['C'].width = 10
        ws.column_dimensions['D'].width = 20
        ws.column_dimensions['E'].width = 20
        ws.column_dimensions['F'].width = 20
        ws.column_dimensions['G'].width = 20
        ws.column_dimensions['H'].width = 20
        ws.column_dimensions['I'].width = 20
        ws.column_dimensions['J'].width = 20
        for row in range(rows.count()):
            atr_list = []
            if rows[row].inventory is None and rows[row].get_last_otklonenie() == '-':
                atr_list = [rows[row].object_name.object_name, rows[row].height, rows[row].weight, rows[row].type,
                            rows[row].date_birth, rows[row].otjazhki_count, '-', '-', '-', '-', rows[row].height]
            elif rows[row].inventory is None and rows[row].get_last_otklonenie() != '-':
                atr_list = [rows[row].object_name.object_name, rows[row].height, rows[row].weight, rows[row].type,
                            rows[row].date_birth, rows[row].otjazhki_count, '-', '-', '-',
                            rows[row].get_last_otklonenie().results, rows[row].height]
            elif rows[row].get_last_otklonenie() == '-' and rows[row].inventory is not None:
                atr_list = [rows[row].object_name.object_name, rows[row].height, rows[row].weight, rows[row].type,
                            rows[row].date_birth, rows[row].otjazhki_count, rows[row].inventory.inventory_number,
                            rows[row].inventory.owner, rows[row].inventory.inventory_name, '-', rows[row].height]
            else:
                atr_list = [rows[row].object_name.object_name, rows[row].height, rows[row].weight, rows[row].type,
                            rows[row].date_birth, rows[row].otjazhki_count, rows[row].inventory.inventory_number,
                            rows[row].inventory.owner, rows[row].inventory.inventory_name,
                            rows[row].get_last_otklonenie().results, rows[row].height]
            ws.cell(row + 2, 7).number_format = BUILTIN_FORMATS[1]
            for col_num in range(len(atr_list)):
                ws.cell(row + 2, col_num + 1, atr_list[col_num])
                ws.cell(row + 2, col_num + 1).font = font2
                ws.cell(row + 2, col_num + 1).border = border
                ws.cell(row + 2, col_num + 1).alignment = alignment
        wb.save(response)
        return response


@login_required(login_url='account:login')
@is_staff
def delete_ams(request, ams_id):
    try:
        ams = Ams.objects.get(id=ams_id)
        ams.delete()
        return redirect('ams:ams')
    except ObjectDoesNotExist:
        return redirect('ams:ams')


@login_required(login_url='account:login')
def ams_detail(request, ams_id, msg=''):
    type_form = AmsTypeForm()
    scheme_form = SchemeForm()
    foto_form = FotoAmsForm()
    diagnostic_form = DiagnosticForm()
    protocol_form = ProtocolForm()
    project_form = ProjectForm()
    sez_form = SezForm()
    inventory_form = InventoryForm()
    inventory = Inventory.objects.all()
    passport_form = PassportForm()
    try:
        ams_object = Ams.objects.get(id=ams_id)

ams/templates/ams/templates/ams_list.html
{% extends "main/templates/layout.html" %}
{% block title %}АМС{% endblock %}
{% block content %}
    <div class="button-bar">
        <span>
            <form action="{% url 'ams:ams_create' %}">
                <button type="submit" value="Создать">Создать объект</button>
            </form>
        </span>
        <span>
            <a href="{% url 'ams:export_xls_ams' %}?{{ request.GET.urlencode }}">
                <button type="submit">Выгрузить</button>
            </a>
        </span>
        {{ msg }}
        <div id="filter-button">
            <span>
                {% if filtered_by == '' %} Фильтрация отсутствует.
                {% else %} Объекты отфильтрованы по: {{ filtered_by }}</span>
                {% endif %}
            <button type="submit" form="filter_reset" value="Сбросить" >Сбросить</button>
            <input type="button" value="Фильтр" onmousedown="showhide('filter')" id="filter-button-dynamic">
            <form id="filter_reset">
                <a href={% url 'ams:ams' %}>
                </a>
            </form>
        </div>
    </div>
    <!-----------------------------------------filter----------------------------------------------------------------->
    <div id="filter">
            <div class="filter-content">
                <form id="filter_form" method="get" action="{% url 'ams:ams' %}">
                    {% csrf_token %}
                    {{ filter_form.as_p }}
                    <span>Выбрать АМС высотой</span>
                    <p>
                       от <input type="number" name="min_visota" min="0" max="300" value="0"> м до
                        <input type="number" name="max_visota" min="0" max="300" value="300"> м
                    </p>
                    <span>Выбрать АМС по отклонению</span>
                    <p>
                        <select name="otklonenie" form="filter_form">
                            <option value="all" selected>Показать все</option>
                            <option value="1">Показать с отклонением</option>
                            <option value="0">Показать без отклонения</option>
                            <option value="2">Показать АМС для которых отсутствуют результаты измерений</option>
                        </select>
                    </p>
                </form>
            </div>
            <div id="filter-button-bar">
                <button type="submit" form="filter_form" value="Применить">Применить</button>
            </div>
    <!-----------------------------------------ajax------------------------------------------------------------>
    <script src="/static/main/script/jquery.js"></script>
    <script src="/static/main/script/filter.js"></script>
    <!-----------------------------------------ajax------------------------------------------------------------>
    </div>
    <div class="content">
        <!-------------------------------------------------------------------->
        {% for i in object %}
        <div id="delete_ams_{{ i.id }}" class="change_form_ozp">
            <form method="post" action="{% url 'ams:delete_ams' i.id %}">
                {% csrf_token %}
                Вы действительно хотите удалить запись???
                <br><br>
                <input type="submit" value="Удалить">
                <button onmousedown="showhide_changeform('delete_ams_{{ i.id }}')" class="close_button">
                <i class="fa-solid fa-xmark"></i>
                </button>
            </form>
        </div>
        {% endfor %}
        <!-------------------------------------------------------------------->
        <div class="table">
            <table>
                <tr class="head_row">
                    <th>Детали</th>
                    <th>Объект</th>
                    <th>Высота АМС</th>
                    <th>Тип АМС</th>
                    <th>ПД</th>
                    <th>ДО</th>
                    <th>Измерения</th>
                    <th>СЭЗ</th>
                    <th>Схема</th>
                    <th>Паспорт</th>
                    <th>Фото</th>
                    <th>Отклонение</th>
                </tr>
                {% if object %}
                    {% for i in object %}
                        <tr class="table_row">
                            <td align="center">
                                <a href="{{ i.get_absolute_url }}" class="ozp-link">
                                    <img src="/static/ams/img/strelka.png" height="50" width="50" alt="детали">
                                </a>
                            </td>
                            <td>{{ i.object_name }}</td>
                            <td align="center">{{ i.height }} м</td>
                            <td align="center">{{ i.type }}</td>
                            <td align="center">
                                {% if i.project.all %}
                                    <a href="{% url 'ams:project_list' i.id %}">
                                        <i class="fa-regular fa-folder-open"></i>
                                    </a>
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                            <td align="center">
                                {% if i.diagnostic.all %}
                                    <a href="{% url 'ams:do_list' i.id %}">
                                        <i class="fa-regular fa-folder-open"></i>
                                    </a>
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                            <td align="center">
                                {% if i.protocol.all %}
                                    <a href="{% url 'ams:measurement_list' i.id %}">
                                        <i class="fa-regular fa-folder-open"></i>
                                    </a>
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                            <td align="center">
                                {% if i.sez.all %}
                                    <a href="{% url 'ams:sez_list' i.id %}">
                                        <i class="fa-regular fa-folder-open"></i>
                                    </a>
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                            <td align="center">
                                {% if i.scheme %}
                                    <a href="{{ i.scheme.url }}">
                                        <i class="fa-regular fa-file-lines"></i>
                                    </a>
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                            <td align="center">
                                {% if i.passport %}
                                    <a href="{{ i.passport.url }}">
                                        <i class="fa-regular fa-file-lines"></i>
                                    </a>
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                            <td align="center">
                                {% if i.foto.all %}
                                    <a href="{% url 'ams:foto_list' i.id %}">
                                        <i class="fa-regular fa-folder-open"></i>
                                    </a>
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                            <td align="center">
                            {% if i.protocol.all %}
                                {% if i.get_last_otklonenie.is_otklonenie %}
                                    <img src="/static/main/img/Exclamation-Mark-Transparent-PNG.png" height="20" width="20">
                                    {{ i.get_last_otklonenie.otklonenie }} мм
                                {% else %}
                                    <img src="/static/main/img/free-png.ru-39.png" height="20" width="20">
                                {% endif %}
                            {% else %}
                                -
                            {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <p>Записи отсутствуют</p>
                {% endif %}
            </table>
        </div>
    </div>
{% endblock %}

ams/templates/ams/templates/do_list.html
{% extends "main/templates/layout.html" %}
{% block title %}Результаты диагностического обследования{% endblock %}
{% block content %}
    <div class="button-bar">
        <span>
            <button onmousedown="showhide_changeform('do')">
                Добавить
            </button>
        </span>
        <span>
            <a href="{% url 'ams:ams' %}">
                <button type="submit" >Назад</button>
            </a>
        </span>
        {{ msg }}
    </div>
    <div class="content">
        <!-------------------------------------------------------------------->
        {% for i in do_list %}
        <div id="do_delete_{{ i.id }}" class="change_form_ozp">
            <form method="post" action="{% url 'ams:do_delete' i.id %}">
                {% csrf_token %}
                Вы действительно хотите удалить запись???
                <br><br>
                <input type="submit" value="Удалить">
                <button onmousedown="showhide_changeform('do_delete_{{ i.id }}')" class="close_button">
                    <i class="fa-solid fa-xmark"></i>
                </button>
            </form>
        </div>
        {% endfor %}
        <!-------------------------------------------------------------------->
        <div id="do" class="change_form_ozp">
            <form method="post" action="{% url 'ams:add_do_list' ams.id %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ diagnostic_form.as_p }}
                <input type="submit" value="Добавить">
                <button onmousedown="showhide_changeform('do')" class="close_button">
                    <i class="fa-solid fa-xmark"></i>
                </button>
            </form>
        </div>
        <!-------------------------------------------------------------------->
        <div class="table">
            <table>
                <tr class="head_row">
                    <th>Дата</th>
                    <th>Документация</th>
                    <th>Удалить</th>
                </tr>
                {% if do_list %}
                    {% for i in do_list %}
                        <tr class="table_row">
                            <td>{{ i.year }}</td>
                            <td align="center">
                                <a href="{{ i.result.url }}" target="_blank">
                                    <i class="fa-solid fa-file-lines"></i>
                                </a>
                            </td>
                            <td align="center">
                                <button onmousedown="showhide_changeform('do_delete_{{ i.id }}')" class="close_button">
                                    <i class="fa-solid fa-trash"></i>
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <p>Записи отсутствуют</p>
                {% endif %}
            </table>
        </div>
    </div>
{% endblock %}

ams/templates/ams/templates/foto_list.html
{% extends "main/templates/layout.html" %}
{% block title %}Фотографии АМС{% endblock %}
{% block content %}
    <div class="button-bar">
        <span>
            <button onmousedown="showhide_changeform('foto')">
                Добавить
            </button>
        </span>
        <span>
            <a href="{% url 'ams:ams' %}">
                <button type="submit" >Назад</button>
            </a>
        </span>
        {{ msg }}
    </div>
    <div class="content">
        <!-------------------------------------------------------------------->
        {% for i in foto_list %}
        <div id="foto_delete_{{ i.id }}" class="change_form_ozp">
            <form method="post" action="{% url 'ams:foto_list_delete' i.id %}">
                {% csrf_token %}
                Вы действительно хотите удалить фотографию???
                <br><br>
                <input type="submit" value="Удалить">
                <button onmousedown="showhide_changeform('foto_delete_{{ i.id }}')" class="close_button">
                    <i class="fa-solid fa-xmark"></i>
                </button>
            </form>
        </div>
        {% endfor %}
        <!-------------------------------------------------------------------->
        <div id="foto" class="change_form_ozp">
            <form method="post" action="{% url 'ams:add_foto_list' ams.id %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ foto_form.as_p }}
                <input type="submit" value="Добавить">
                <button onmousedown="showhide_changeform('foto')" class="close_button">
                    <i class="fa-solid fa-xmark"></i>
                </button>
            </form>
        </div>
        <!-------------------------------------------------------------------->
        <div class="table">
            {% for i in foto_list %}
                <div class="foto_ams_list">
                    <a href="{{ i.foto.url }}" target="_blank">
                        <img src="{{ i.foto.url }}">
                    </a>
                    <button onmousedown="showhide_changeform('foto_delete_{{ i.id }}')" class="foto_button">
                        <i class="fa-solid fa-trash"></i>
                    </button>
                    <div class="foto_text">
                        {{ i.year.year }}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

ams/templates/ams/templates/main_ams.html
{% extends "main/templates/layout.html" %}
{% block content %}
    <P2>GHbdtn</P2>
{% endblock %}