ams/urls.py
from django.urls import path
from . import views

app_name = 'ams'
urlpatterns = [
    path('', views.ams, name='ams'),
    path('ams_create/', views.ams_create, name='ams_create'),
    path('export_xls_ams/', views.export_xls_ams, name='export_xls_ams'),
    path('delete_ams/<int:ams_id>/', views.delete_ams, name='delete_ams'),
    path('ams_detail/<int:ams_id>/<str:msg>/', views.ams_detail, name='ams_detail'),
    path('ams_detail/<int:ams_id>/', views.ams_detail, name='ams_detail'),
    path('change_height/<int:ams_id>/', views.change_height, name='change_height'),
    path('change_weight/<int:ams_id>/', views.change_weight, name='change_weight'),
    path('change_type/<int:ams_id>/', views.change_type, name='change_type'),
    path('change_date/<int:ams_id>/', views.change_date, name='change_date'),
    path('change_scheme/<int:ams_id>/', views.change_scheme, name='change_scheme'),
    path('delete_scheme/<int:ams_id>/', views.delete_scheme, name='delete_scheme'),
    path('foto_ams_add/<int:ams_id>', views.foto_ams_add, name='foto_ams_add'),
    path('foto_delete/<int:foto_id>/', views.foto_delete, name='foto_delete'),
    path('add_protocol/<int:ams_id>/', views.add_protocol, name='add_protocol'),
    path('add_diagnostic/<int:ams_id>/', views.add_diagnostic, name='add_diagnostic'),
    path('add_project/<int:ams_id>/', views.add_project, name='add_project'),
    path('add_sez/<int:ams_id>/', views.add_sez, name='add_sez'),
    path('add_inventory/<int:ams_id>/', views.add_inventory, name='add_inventory'),
    path('select_inventory/<int:ams_id>', views.select_inventory, name='select_inventory'),
    path('add_passport/<int:ams_id>', views.add_passport, name='add_passport'),
    path('delete_passport/<int:ams_id>/', views.delete_passport, name='delete_passport'),
    path('project_list/<int:ams_id>/', views.project_list, name='project_list'),
    path('project_list/<int:ams_id>/<str:msg>/', views.project_list, name='project_list'),
    path('project_delete/<int:project_id>/', views.project_delete, name='project_delete'),
    path('add_project_list/<int:ams_id>/', views.add_project_list, name='add_project_list'),
    path('do_list/<int:ams_id>/', views.do_list, name='do_list'),
    path('do_list/<int:ams_id>/<str:msg>/', views.do_list, name='do_list'),
    path('do_delete/<int:do_id>/', views.do_delete, name='do_delete'),
    path('add_do_list/<int:ams_id>/', views.add_do_list, name='add_do_list'),
    path('measurement_list/<int:ams_id>/', views.measurement_list, name='measurement_list'),
    path('measurement_list/<int:ams_id>//<str:msg>', views.measurement_list, name='measurement_list'),
    path('measurement_delete/<int:measurement_id>/', views.measurement_delete, name='measurement_delete'),
    path('add_measurement_list/<int:ams_id>/', views.add_measurement_list, name='add_measurement_list'),
    path('sez_list/<int:ams_id>/', views.sez_list, name='sez_list'),
    path('sez_list/<int:ams_id>/<str:msg>', views.sez_list, name='sez_list'),
    path('sez_delete/<int:sez_id>/', views.sez_delete, name='sez_delete'),
    path('add_sez_list/<int:ams_id>/', views.add_sez_list, name='add_sez_list'),
    path('foto_list/<int:ams_id>/', views.foto_list, name='foto_list'),
    path('foto_list/<int:ams_id>/<str:msg>/', views.foto_list, name='foto_list'),
    path('foto_list_delete/<int:foto_id>', views.foto_list_delete, name='foto_list_delete'),
    path('add_foto_list/<int:ams_id>/', views.add_foto_list, name='add_foto_list')
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('ams/', include('ams.urls')),
    path('rich/', include('rich.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                             document_root=settings.MEDIA_ROOT)

rich/urls.py
from django.urls import path
from . import views

app_name = 'rich'
urlpatterns = [
    path('', views.rich_index, name='rich_index'),
    path('res_create/', views.res_creation, name='res_create'),
    path('res_detail/<int:id>/', views.res_detail, name='res_detail'),
    path('change_name/<int:id>/', views.change_name, name='change_name'),
    path('change_object/<int:id>/', views.change_object, name='change_object'),
    path('change_rich/<int:id>/', views.change_rich, name='change_rich'),
    path('add_rich/<int:id>/', views.add_rich, name='add_rich'),
    path('change_registration/<int:id>/', views.change_registration, name='change_registration'),
    path('add_registration/<int:id>/', views.add_registration, name='add_registration'),
    path('change_radio_class/<int:id>', views.change_radio_class, name='change_radio_class'),
    path('antenna_height_change/<int:id>', views.antenna_height_change, name='antenna_height_change'),
    path('antenna_azimuth_change/<int:id>', views.antenna_azimuth_change, name='antenna_azimuth_change'),
    path('antenna_gain_change/<int:id>', views.antenna_gain_change, name='antenna_gain_change'),
    path('antenna_polarization_change/<int:id>/', views.antenna_polarization_change, name='antenna_polarization_change'),
    path('rich_app_index', views.rich_app_index, name='rich_app_index'),
    path('rich_list', views.rich_list, name='rich_list'),
    path('rich_create', views.rich_create, name='rich_create'),
    path('delete_rich/<int:id>', views.delete_rich, name='delete_rich'),
    path('export_xls_rich', views.export_xls_rich, name='export_xls_rich'),
    path('reg_list', views.reg_list, name='reg_list'),
    path('delete_reg/<int:key>', views.delete_reg, name='delete_reg'),
    path('reg_create', views.reg_create, name='reg_create'),
    path('ajax/load-res/', views.load_res, name='ajax_load_res'),
    path('export_xls_reg/', views.export_xls_reg, name='export_xls_reg'),
    path('res_export_xls/', views.res_export_xls, name='res_export_xls'),
    path('delete_res/<int:key>', views.delete_res, name='delete_res'),
    path('equip_list/', views.equip_list, name='equip_list'),
    path('equip_delete/<int:key>/', views.equip_delete, name='equip_delete'),
    path('equip_create/', views.equip_create, name='equip_create'),
    path('add_equipment/<int:key>/', views.add_equipment, name='add_equipment'),
    path('change_equipment/<int:key>', views.change_equipment, name='change_equipment'),
    path('protokol_list/<int:key>/', views.protokol_list, name='protokol_list'),
    path('protocol_delete/<int:key>', views.protocol_delete, name='protocol_delete'),
    path('add_res_protokol/<int:key>/', views.add_res_protokol, name='add_res_protokol'),
    path('add_res_protokol_list/<int:key>/', views.add_res_protokol_list, name='add_res_protokol_list')
]

rich/models.py
from datetime import date

from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.core.validators import FileExtensionValidator, MaxValueValidator, MinValueValidator
from main.models import Object
from django.shortcuts import reverse
from pathlib import Path

from rich.scripts import numeral_noun_declension


class Type(models.Model):
    name: str = models.CharField(max_length=50, verbose_name='Введите наименование оборудования')
    manufacter = models.CharField(max_length=50, blank=True, null=True, verbose_name='Укажите производителя '
                                                                                     'оборудования')
    fs_form = models.FileField(upload_to='files/', verbose_name='Загрузите форму общих технических данных',
                               validators=[FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'],
                                                                  message='Тип файла выбран неверно.')])
    frequency_range_min = models.IntegerField(verbose_name='Укажите минимальную частоту обордуования, Гц',
                                              validators=[MaxValueValidator(90000000000, message='Значение частоты не '
                                                                                                 'может быть больше 90 '
                                                                                                 'ГГц'),
                                                          MinValueValidator(0, message='Значение частоты не может быть '
                                                                                       'меньше 0')])
    frequency_range_max = models.IntegerField(verbose_name='Укажите максимальную частоту обордуования, Гц',
                                              validators=[MaxValueValidator(90000000000, message='Значение частоты не '
                                                                                                 'может быть больше '
                                                                                                 '90 ГГц'),
                                                          MinValueValidator(0, message='Значение частоты не может быть '
                                                                                       'меньше 0')])
    CLASS_CHOICES = [
        ('РРЛ', 'РРЛ'),
        ('БС конвенциональной связи', 'БС конвенциональной связи'),
        ('БС транкинговой связи', 'БС транкинговой связи'),
        ('БС', 'БС'),
        ('РЭС морской подвижной службы', 'РЭС морской подвижной службы'),
        ('РЭС сухопутной подвижной службы', 'РЭС сухопутной подвижной службы'),
        ('Судовые РЭС', 'Судовые РЭС'),
        ('АС', 'АС')]
    class_name = models.CharField(max_length=50, choices=CLASS_CHOICES, verbose_name='Выберите класс РЭС')
    frequency_str = models.CharField(max_length=50, null=True, default=None)
    # frequency_str представление в виде строки для фильтрации по диапазонам заполняется автоматически функцией
    # frequency_range

    def __str__(self):
        return self.name

    def frequency_range(self):
        # frequency_range функция поучения строки диапазона
        div = 1
        units = 'Гц'
        if 1000000 > self.frequency_range_max >= 1000:
            div = 1000
            units = 'кГц'
        elif 1000000000 > self.frequency_range_max >= 1000000:
            div = 1000000
            units = 'МГц'
        elif self.frequency_range_max >= 1000000000:
            div = 1000000000
            units = 'ГГц'
        if 1000000 > self.frequency_range_min >= 1000:
            div = 1000
            units = 'кГц'
        elif 1000000000 > self.frequency_range_min >= 1000000:
            div = 1000000
            units = 'МГц'
        elif self.frequency_range_min >= 1000000000:
            div = 1000000000
            units = 'ГГц'
        frequency_string = str(int(self.frequency_range_max/div)) + ' ' + units + ' - ' + \
                           str(int(self.frequency_range_min/div)) + ' ' + units
        self.frequency_str = frequency_string
        self.save()
        return frequency_string


class Rich(models.Model):
    name = models.CharField(max_length=50, verbose_name='Наименование', unique=True)
    start_date = models.DateField(auto_now=False, auto_now_add=False, verbose_name='Дата начала действия РИЧ')
    end_date = models.DateField(auto_now=False, auto_now_add=False, verbose_name='Дата окончания действия РИЧ')
    doc = models.FileField(upload_to='files/', validators=[FileExtensionValidator(allowed_extensions=['png', 'jpeg',
                                                                                                      'tiff', 'bmp',
                                                                                                      'gif', 'pdf',
                                                                                                      'doc', 'docx'],
                                                                                  message='Тип файла выбран неверно.')],
                           verbose_name='Копия разрешения')
    is_active = models.BooleanField()

    class Meta:
        ordering = ['-is_active', 'end_date']

    def save(self, *args, **kwargs):
        x = str(Path(self.doc.name).name.replace(Path(self.doc.name).suffix, ''))
        self.name = x.replace('_', ' ')
        if self.end_date < date.today():
            self.is_active = False
            try:
                res_obj = Res.objects.filter(related_rich=self)
                for i in res_obj:
                    i.related_rich = None
                    i.save()
            except ObjectDoesNotExist:
                pass
        else:
            self.is_active = True
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def days_left(self):
        now = date.today()
        if self.end_date < now:
            self.save()
            return 'РИЧ недействителен'
        else:
            d = self.end_date - now
            self.save()
            result = str(d.days) + ' ' + numeral_noun_declension(d.days, 'день', 'дня', 'дней')
            return result


class Registration(models.Model):
    name = models.CharField(max_length=50, verbose_name='Наименование', unique=True, null=True, blank=True)
    start_date = models.DateField(auto_now=False, auto_now_add=False, verbose_name='Укажите дату начала действия')
    end_date = models.DateField(auto_now=False, auto_now_add=False, verbose_name='Укажите дату окончания срока '
                                                                                 'действия')
    doc = models.FileField(upload_to='files/', validators=[FileExtensionValidator(allowed_extensions=['png', 'jpeg',
                                                                                                      'tiff', 'bmp',
                                                                                                      'gif', 'pdf',
                                                                                                      'doc', 'docx'],
                                                                                  message='Тип файла выбран неверно.')],
                           verbose_name='Копия свидетельства')
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        x = str(Path(self.doc.name).name.replace(Path(self.doc.name).suffix, ''))
        self.name = x.replace('_', ' ')
        if self.end_date < date.today():
            self.is_active = False
            try:
                res_obj = Res.objects.get(related_registration=self)
                res_obj.related_registration = None
                res_obj.save()
            except ObjectDoesNotExist:
                pass
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def days_left(self):
        now = date.today()
        if self.end_date < now:
            self.save()
            return 'Регистрация недействителена'
        else:
            d = self.end_date - now
            result = str(d.days) + ' ' + numeral_noun_declension(d.days, 'день', 'дня', 'дней')
            return result


class Res(models.Model):
    POLARIZATION_CHOICES = [
        ('Вертикальная', 'Вертикальная'),
        ('Горизонтальная', 'Горизонтальная'),
        ('Круговая', 'Круговая')]
    name = models.CharField(verbose_name='Наименование', max_length=20)
    related_object = models.ForeignKey(Object, on_delete=models.CASCADE, related_name='res', verbose_name='Укажите '
                                                                                                          'объект '
                                                                                                          'установки')
    related_rich = models.ForeignKey(Rich, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Выберите '
                                                                                                          'РИЧ',
                                     related_name='related_res')
    related_registration = models.OneToOneField(Registration, on_delete=models.SET_NULL, blank=True, null=True,
                                                verbose_name='Выберите регистрацию', related_name='related_res_reg')
    radio_class = models.CharField(max_length=20, blank=True, null=True, verbose_name='Введите класс излучения')
    antenna_height = models.IntegerField(blank=True,
                                         null=True,
                                         verbose_name='Укажите высоту установки антенны',
                                         validators=[
                                             MaxValueValidator(200, message='Значение высоты подвеса антенны не может '
                                                                            'быть больше 200'),

rich/templates/rich/templates/res_list_options.html
<option value="">выбрать</option>
{% for res in res_list %}
<option value="{{ res.pk }}">{{ res.name }}</option>
{% endfor %}

rich/templates/rich/templates/rich_app_index.html
{% extends "main/templates/layout.html" %}
{% block content %}
            <div class="button">
                <a href="{% url 'rich:rich_index' %}" id="res_button">
                <span class="button-text">РЭС</span>
                </a>
            </div>
            <div class="button">
                <a href="{% url 'rich:rich_list' %}" id="rich_button">
                <span class="button-text">РИЧ</span>
                </a>
            </div>
            <div class="button" >
                <a href="{% url 'rich:reg_list' %}" id="registration_button">
                <span class="button-text">Регистрация</span>
                </a>
            </div>
{% endblock %}

rich/templates/rich/templates/rich_index.html
{% extends "main/templates/layout.html" %}
{% block title %}Список объектов{% endblock %}
{% block content %}
    <div class="button-bar">
        <span>
            <form action="{% url 'rich:res_create' %}">
                <button type="submit" value="Создать">Создать запись</button>
            </form>
        </span>
        <span>
            <a href="{% url 'rich:res_export_xls' %}?{{ request.GET.urlencode }}">
                <button type="submit">Выгрузить</button>
            </a>
        </span>
        <div id="filter-button">
            <span>
                {% if filtered_by == '' %} Фильтрация отсутствует.
                {% else %} Объекты отфильтрованы по: {{ filtered_by }}</span>
                {% endif %}
            <button type="submit" form="filter_reset" value="Сбросить" >Сбросить</button>
            <input type="button" value="Фильтр" onmousedown="showhide('filter')" id="filter-button-dynamic">
            <form id="filter_reset">
                <a href={% url 'rich:rich_index' %}></a>
            </form>
        </div>
    </div>
    <div id="filter">
            <div class="filter-content">
                <form id="filter_form" method="get" action={% url 'rich:rich_index' %}>
                    {% csrf_token %}
                    {{ filter_form.as_p }}
                    <span>Фильтровать по дейструющим:</span>
                    <p>
                        <select name="is_active" form="filter_form">
                            <option value="all">Показать все</option>
                            <option value="1">Показать только действующие</option>
                            <option value="0">Показать только проектируемые</option>
                        </select>
                    </p>
                    <span>Фильтровать типу РЭС:</span>
                    <p>
                        <select name="type_res" form="filter_form">
                            <option value="all">Показать все</option>
                            {% for i in type_list %}
                               <option value="{{ i.class_name }}">{{ i.class_name }}</option>
                            {% endfor %}
                        </select>
                    </p>
                    <span>Фильтровать по наименованию оборудования:</span>
                    <p>
                        <select name="equip_name" form="filter_form">
                            <option value="all">Показать все</option>
                            {% for i in type_list %}
                               <option value="{{ i }}">{{ i }}</option>
                            {% endfor %}
                        </select>
                    </p>
                    <span>Фильтровать по диапазону:</span>
                    <p>
                        <select name="frequency_range" form="filter_form">
                            <option value="all">Показать все</option>
                            {% for i in type_list %}
                               <option value="{{ i.frequency_str }}">{{ i.frequency_str }}</option>
                            {% endfor %}
                        </select>
                    </p>
                </form>
            </div>
            <div id="filter-button-bar">
                <button type="submit" form="filter_form" value="Применить">Применить</button>
            </div>
        <!-----------------------------------------ajax------------------------------------------------------------>
        <script src="/static/main/script/jquery.js"></script>
        <script src="/static/main/script/filter.js"></script>
        <!-----------------------------------------ajax------------------------------------------------------------>
    </div>
    <div class="content">
        <!-------------------------------------------------------------------->
        {% for i in object %}
        <div id="delete_res_{{ i.id }}" class="change_form_ozp">
            <form method="post" action="{% url 'rich:delete_res' i.id %}">
                {% csrf_token %}
                Вы действительно хотите удалить запись???
                <br><br>
                <input type="submit" value="Удалить">
                <button onmousedown="showhide_changeform('delete_res_{{ i.id }}')" class="close_button">
                <i class="fa-solid fa-xmark"></i>
                </button>
            </form>
        </div>
        {% endfor %}
        <!-------------------------------------------------------------------->
        <div class="table">
            <table>
                <tr class="head_row">
                    <th>РЭС</th>
                    <th>Тип РЭС</th>
                    <th>Оборудование</th>
                    <th>Объект</th>
                    <th>РИЧ</th>
                    <th>Срок действия РИЧ</th>
                    <th>Свидетельство</th>
                    <th>Срок действия регистрации</th>
                    <th>Протокол</th>
                    <th>В работе</th>
                    <th>Удалить</th>
                </tr>
                {% if object %}
                    {% for i in object %}
                        <tr class="table_row">
                            <td align="center">
                                <a href="{{ i.get_absolute_url }}">
                                {{ i }}
                                </a>
                            </td>
                            <td>
                                {% if i.type %}
                                    {{ i.type.class_name }}
                                {% else %}
                                    Не выбрано
                                {% endif %}
                            </td>
                            <td>
                                {% if i.type %}
                                    {{ i.type }}
                                {% else %}
                                    Не выбран
                                {% endif %}
                            </td>
                            <td>{{ i.related_object }}</td>
                            <td align="center">
                                {% if i.related_rich %}
                                    <a href="{{ i.related_rich.doc.url }}">
                                        <i class="fa-regular fa-file-lines"></i>
                                    </a>
                                {% else %}
                                    РИЧ не присвоен
                                {% endif %}
                            </td>
                            <td>
                                {% if i.related_rich %}
                                    {{ i.related_rich.days_left }}
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                            <td align="center">
                                {% if i.related_registration %}
                                    <a href="{{ i.related_registration.doc.url }}">
                                        <i class="fa-regular fa-file-lines"></i>
                                    </a>
                                {% else %}
                                    РЭС не зарегистрирован
                                {% endif %}
                            </td>
                            <td>
                                {% if i.related_registration %}
                                    {{ i.related_registration.days_left }}
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                            <td align="center">
                                {% if i.protokol.all %}
                                    <a href="{% url 'rich:protokol_list' i.id %}"><i class="fa-solid fa-folder-open"></i></a>
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                            <td>{{ i.active_status }}</td>
                            <td align="center">
                                <button onmousedown="showhide_changeform('delete_res_{{ i.id }}')" class="close_button">
                                    <i class="fa-solid fa-trash"></i>
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <p>РЭС с указанными критериями поиска отсутствуют</p>
                {% endif %}
            </table>
        </div>
    </div>
{% endblock %}

rich/templates/rich/templates/rich_list.html
{% extends "main/templates/layout.html" %}
{% block title %}Список объектов{% endblock %}
{% block content %}
    <div class="button-bar">
        <span>
            <form action="{% url 'rich:rich_create' %}">
                <button type="submit" value="Создать">Создать запись</button>
            </form>
        </span>
        <span>
            <a href="{% url 'rich:export_xls_rich' %}?{{ request.GET.urlencode }}">
                <button type="submit">Выгрузить</button>
            </a>
        </span>
        <div id="filter-button">
            <span>
                {% if filtered_by == '' %} Фильтрация отсутствует.
                {% else %} Объекты отфильтрованы по: {{ filtered_by }}</span>
                {% endif %}
            <button type="submit" form="filter_reset" value="Сбросить" >Сбросить</button>
            <input type="button" value="Фильтр" onmousedown="showhide('filter')" id="filter-button-dynamic">
            <form id="filter_reset">
                <a href={% url 'rich:rich_index' %}>
                </a>
            </form>
        </div>
    </div>
    <div id="filter">
            <div class="filter-content">
                <form id="filter_form" method="get" action={% url 'rich:rich_list' %}>
                    {% csrf_token %}
                    {{ filter_form.as_p }}
                    <span>Фильтровать по действующим:</span>
                    <p>
                        <select name="is_active" form="filter_form">
                            <option value="all" selected>Показать все</option>
                            <option value="1">Показать только действующие</option>
                            <option value="0">Показать только недействительные</option>
                        </select>
                    </p>
                    <span>Показать РИЧ со сроком окончания в текущем году:</span>
                    <p>
                        <select name="srok_this_year" form="filter_form">
                            <option value="all">Показать все</option>
                            <option value="1">Показать РИЧ со сроком действия менее года</option>
                        </select>
                    </p>
                </form>
            </div>
            <div id="filter-button-bar">
                <button type="submit" form="filter_form" value="Применить">Применить</button>
            </div>
    <!-----------------------------------------ajax------------------------------------------------------------>
        <script src="/static/main/script/jquery.js"></script>
        <script src="/static/main/script/filter.js"></script>
    <!-----------------------------------------ajax------------------------------------------------------------>
    </div>
    <div class="content">
        <!-------------------------------------------------------------------->
        {% for i in object %}
        <div id="delete_rich_{{ i.id }}" class="change_form_ozp">
            <form method="post" action="{% url 'rich:delete_rich' i.id %}">
                {% csrf_token %}
                Вы действительно хотите удалить запись???
                <br><br>
                <input type="submit" value="Удалить">
                <button onmousedown="showhide_changeform('delete_rich_{{ i.id }}')" class="close_button">
                <i class="fa-solid fa-xmark"></i>
                </button>
            </form>
        </div>
        {% endfor %}
        <!-------------------------------------------------------------------->
        <div class="table">
            <table>
                <tr class="head_row">
                    <th>РИЧ</th>
                    <th>Дата начала действия РИЧ</th>
                    <th>Дата окончания РИЧ</th>
                    <th>Срок действия РИЧ</th>
                    <th>Перечень РЭС</th>
                    <th>Удалить</th>
                </tr>
                {% if object %}
                    {% for i in object %}
                        <tr class="table_row">
                            <td align="center">
                                <a href="{{ i.doc.url }}" class="ozp-link">
                                {{ i.name }}
                                </a>
                            </td>
                            <td>{{ i.start_date}}</td>
                            <td>{{ i.end_date }}</td>
                            <td>{{ i.days_left }}</td>
                            <td>
                                {% for x in i.related_res.all %}
                                    <a href="{{ x.get_absolute_url }}">{{ x.name }},</a>
                                {% endfor %}
                            </td>
                            <td align="center">
                                <button onmousedown="showhide_changeform('delete_rich_{{ i.id }}')" class="close_button">
                                    <i class="fa-solid fa-trash"></i>
                                </button>
                            </td>
                        </tr>

                    {% endfor %}
                {% else %}
                    <p>Записи отсутствуют</p>
                {% endif %}
            </table>
        </div>
    </div>
{% endblock %}